version: '3.8'

services:
  app:
    build: .
    container_name: taux-app
    restart: always
    environment:
      - GIN_MODE=release
      - PORT=8080
    ports:
      - "8080:8080" # Exposed for debugging, or if we want to bypass nginx locally

  nginx:
    image: nginx:alpine
    container_name: taux-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
